### ISSUE TITLE
trying to access a non-existing resource returns an empty body

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis-reva#163]
when trying to access a resource that does not exist with GET or PROPFIND, the correct HTTP code (404) is returned but the body of the response is empty

```
curl -X PROPFIND http://localhost:9140/remote.php/dav/files/does-not-exist -u user0:123456 -v
*   Trying 127.0.0.1:9140...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9140 (#0)
* Server auth using Basic with user 'user0'
> PROPFIND /remote.php/dav/files/does-not-exist HTTP/1.1
> Host: localhost:9140
> Authorization: Basic dXNlcjA6MTIzNDU2
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Access-Control-Allow-Origin: *
< Vary: Origin
< X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJyZXZhIiwiZXhwIjoxNTg4NTc1NTkxLCJpYXQiOjE1ODg1NzE5OTEsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjkyMDAiLCJ1c2VyIjp7ImlkIjp7ImlkcCI6Imh0dHBzOi8vbG9jYWxob3N0OjkyMDAiLCJvcGFxdWVfaWQiOiJ1c2VyMCJ9LCJ1c2VybmFtZSI6InVzZXIwIiwibWFpbCI6InVzZXIwQGV4YW1wbGUub3JnIiwiZGlzcGxheV9uYW1lIjoiVXNlciBaZXJvIn19.7idBBYb4GuSQB3LQxZIMf4JmWz-teFBzpKZX1_PVIiU
< Date: Mon, 04 May 2020 05:59:51 GMT
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
```

## vs oC 10

```
curl -X PROPFIND http://localhost/owncloud-core/remote.php/dav/files/does-not-exist -u uu1:uu1 -v
*   Trying 127.0.0.1:80...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 80 (#0)
* Server auth using Basic with user 'uu1'
> PROPFIND /owncloud-core/remote.php/dav/files/does-not-exist HTTP/1.1
> Host: localhost
> Authorization: Basic dXUxOnV1MQ==
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Date: Mon, 04 May 2020 06:00:26 GMT
< Server: Apache/2.4.43 (Ubuntu)
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< X-Robots-Tag: none
< X-Frame-Options: SAMEORIGIN
< X-Download-Options: noopen
< X-Permitted-Cross-Domain-Policies: none
< Set-Cookie: oc4kyqahfanl=c9jffpv2t69jkun4u618srq9m0; path=/owncloud-core; HttpOnly
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate
< Pragma: no-cache
< Set-Cookie: oc_sessionPassphrase=RrXPBYcZINaSYO%2FyXa0KD1Dk55%2BXVzUBt0En2u8OR6%2BFmFh5snEXGHK6OubihNmB0d98QfYx4K0WvxmObZizlYzxvOC4rMwhCrCuyrJTVeC8YIZHMJWFyD8mM%2FDw8AMc; path=/owncloud-core; HttpOnly
< Content-Security-Policy: default-src 'none';
< Set-Cookie: oc4kyqahfanl=62cob6c4pgbiat956s91o31t79; path=/owncloud-core; HttpOnly
< Set-Cookie: cookie_test=test; expires=Mon, 04-May-2020 07:00:26 GMT; Max-Age=3600
< Vary: Brief,Prefer
< DAV: 1, 3, extended-mkcol, 2
< Content-Length: 236
< Content-Type: application/xml; charset=utf-8
< 
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>Principal with name does-not-exist not found</s:message>
</d:error>
* Connection #0 to host localhost left intact

**Comment by individual-it** [comment]
similar to #30

**Comment by PVince81** [comment]
supersedes https://github.com/owncloud/ocis-reva/issues/13 as now it returns an empty body with 204 instead of 500.

- [ ] unskip test issue-ocis-reva-13 when fixed

**Comment by PVince81** [comment]
Going to try and debug this

**Comment by PVince81** [comment]
bug seems gone:
```
curl -D - -X PROPFIND -u einstein:relativity -k http://localhost:9140/remote.php/dav/files/does-not-exist
HTTP/1.1 404 Not Found
Access-Control-Allow-Origin: *
Vary: Origin
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJyZXZhIiwiZXhwIjoxNTg4NTg5MzM2LCJpYXQiOjE1ODg1ODU3MzYsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjkyMDAiLCJ1c2VyIjp7ImlkIjp7ImlkcCI6Imh0dHBzOi8vbG9jYWxob3N0OjkyMDAiLCJvcGFxdWVfaWQiOiJlaW5zdGVpbiJ9LCJ1c2VybmFtZSI6ImVpbnN0ZWluIiwibWFpbCI6ImVpbnN0ZWluQGV4YW1wbGUub3JnIiwiZGlzcGxheV9uYW1lIjoiRWluc3RlaW4ifX0.w2caqBfMe6C-loaoLw0JUI4F06C4JTmptEzULxUiJzA
Date: Mon, 04 May 2020 09:48:56 GMT
Content-Length: 0
```

The following was tested manually using curl with the ocis server (without external LDAP docker)

I think we need to distinguish multiple cases properly:
- [x] accessing a non-existing resource with GET inside home: getting 404 :white_check_mark: 
- [x] accessing a non-existing resource with PROPFIND inside home: getting 404 :white_check_mark: 
- [x] accessing a non-existing user in dav2 path "remote.php/dav/files/unexist" with GET : getting 404 :white_check_mark: 
- [x] accessing a non-existing user in dav2 path "remote.php/dav/files/unexist" with PROPFIND: getting 404 :white_check_mark: 
- [x] access a non-existing resource inside **another user's** path "remote.php/dav/files/anotheruser/unexist.txt" with GET: returns 404 :white_check_mark: 
- [x] access a non-existing resource inside **another user's** path "remote.php/dav/files/anotheruser/unexist.txt" with PROPFIND: returns 404 :white_check_mark: 
- [x] access an existing resource inside **another user's** path "remote.php/dav/files/anotheruser/exist.txt" with GET: should return 404 :no_entry_sign: , already reported here: https://github.com/owncloud/ocis-reva/issues/9
- [x] access an existing resource inside **another user's** path "remote.php/dav/files/anotheruser/exist.txt" with PROPFIND: should return 404, returns XML instead :no_entry_sign: https://github.com/owncloud/ocis-reva/issues/9

- [ ] trying to **DELETE** a resource inside **another user's** path returns 204 but should return 404 :no_entry_sign:, likely covered by https://github.com/owncloud/ocis-reva/issues/13#issuecomment-623331357
- [x] trying to **DELETE** a non-existing resource inside own or another user's path returns 404 :white_check_mark: 

To me it seems this already works.

But I have doubts about what https://github.com/owncloud/ocis-reva/issues/13#issuecomment-623331357 is actually testing and why it would still fail, as it seems to be deleting a non-existing file but behaves as if it that file does exist. @individual-it can you recheck ?

**Comment by PVince81** [comment]
@individual-it the top post speaks of a non-existing resource but it's actually a non-existing user or another user.

a non-existing resource would be "http://localhost:9140/remote.php/dav/files/einstein/does-not-exist".

we should be more precise in the future because of all these possible distinctions and nuances, especially that these are likely covered by different code paths in the backend

**Comment by individual-it** [comment]
@PVince81 you are true, I forgot the username in the dav path, but the result is the same - the content of the reply is empty. This issue is not about the return code but about the body of the result message. 

In your test its the same `Content-Length: 0` oC10 returns an XML body in that case, ocis does an empty body

**Comment by PVince81** [comment]
Ah, got it. Thanks

**Comment by PVince81** [comment]
to be discussed in https://github.com/owncloud/ocis-reva/issues/199
